const areaHandle = document.querySelector(".areaHandle");
const boxNumberSelected = document.querySelector(".numberSelected");
const numberSelected = document.querySelectorAll(".box");
const boxRecommend = document.querySelector(".boxRecommend .card-body");
const select_level = document.querySelector(".select_level");
const result = document.querySelector(".body");
var randomNumber;
var num = -1;
var b = 15;
var list=[];
var nameRank="";
var scoreRank = 0;